/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Components.TabbedPaneCustom;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author brici_6ul2f65
 */
public class PaiementPanel extends JPanel {
    private TabbedPaneCustom tabbedPane;

    public PaiementPanel() throws Exception {
        setBorder(new EmptyBorder(4, 5, 2, 0));
        
        // Layout for the main panel (Tabbed Pane)
        tabbedPane = new TabbedPaneCustom();
        tabbedPane.setSelectedColor(new Color(49, 158, 242));
        tabbedPane.setUnselectedColor(new Color(185, 214, 255));
        
        // Add tabs with initial panels
        tabbedPane.addTab("Acompte", new PaiementAcompte());
        tabbedPane.addTab("Facture", null);
        
        // Add change listener to load panels lazily
        tabbedPane.addChangeListener((ChangeEvent e) -> {
            int selectedIndex = tabbedPane.getSelectedIndex();
            if (tabbedPane.getComponentAt(selectedIndex) == null) {
                try {
                    switch (selectedIndex) {
                        case 1 : tabbedPane.setComponentAt(selectedIndex, new PaiementFacture());
                        break;
                        // Add more cases if there are additional tabs to be loaded lazily
                        default :  throw new IllegalStateException("Unexpected tab index: " + selectedIndex);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(PaiementPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        // Create a main panel to hold the tabbed pane
        setLayout(new BorderLayout());
        add(tabbedPane, BorderLayout.CENTER); // Add the tabbed pane to the center
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
